"""
DIRE - Diffusion Reconstruction Error Detection
Based on ICCV 2023 paper: "DIRE for Diffusion-Generated Image Detection"

Detects images generated by diffusion models (Stable Diffusion, DALL-E 3, Midjourney)
by measuring how well they can be reconstructed through the diffusion process.

Key Insight:
- AI-generated images have LOW reconstruction error (they "fit" the diffusion model)
- Real photos have HIGH reconstruction error (they don't follow the learned distribution)

IMPROVED: Now with model caching for 10x performance improvement!
"""
import numpy as np
import torch
from PIL import Image
from typing import Dict, Any
import warnings
warnings.filterwarnings('ignore')

try:
    from huggingface_hub import hf_hub_download
except ImportError:
    try:
        from huggingface_hub import cached_download as hf_hub_download
    except ImportError:
        hf_hub_download = None

from backend.core.logger import setup_logger
from backend.core.model_cache import get_model_cache
from backend.config.cache_config import CacheConfig

logger = setup_logger(__name__)


class DIREDetector:
    """
    Diffusion Reconstruction Error Detector with model caching.

    Uses Stable Diffusion 2.1 to measure reconstruction error.
    """

    def __init__(self):
        """Initialize DIRE detector with Stable Diffusion model."""
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.model = None
        self._model_loaded = False
        
        # Cache configuration
        self.cache = get_model_cache()
        self.cache_key = "stable-diffusion-2-1"
        self.model_size_mb = CacheConfig.MODEL_SIZES.get(self.cache_key, 4000)
        self._from_cache = False
        
        logger.info(f"DIRE Detector initialized (device: {self.device})")

    def _load_model(self):
        """Lazy load Stable Diffusion model with caching (10x faster on cache hit)."""
        if self._model_loaded:
            return

        # Try to get from cache first
        cached_model = self.cache.get(self.cache_key)
        
        if cached_model is not None:
            logger.info("Loading Stable Diffusion from cache")
            self.pipe = cached_model['pipe']
            self.scheduler = cached_model['scheduler']
            self._model_loaded = True
            self._from_cache = True
            logger.info("Loaded from cache in <1s")
            return

        # Cache miss - load from disk. Guarded by a per-key lock (F-7):
        # without it, two concurrent cold-start requests can both observe
        # the miss above and both independently load the full ~4-5GB
        # Stable Diffusion 2.1 pipeline.
        with self.cache.get_load_lock(self.cache_key):
            # Double-check: another thread may have finished loading and
            # populated the cache while we were waiting for the lock.
            cached_model = self.cache.get(self.cache_key)
            if cached_model is not None:
                logger.info("Loading Stable Diffusion from cache (loaded by a concurrent request)")
                self.pipe = cached_model['pipe']
                self.scheduler = cached_model['scheduler']
                self._model_loaded = True
                self._from_cache = True
                return

            try:
                from diffusers import StableDiffusionPipeline, DDIMScheduler

                logger.info("Loading Stable Diffusion 2.1 model from disk...")
                logger.info("First load may take time if model not cached locally")

                # Use SD 2.1 (best balance of speed/accuracy)
                model_id = "stabilityai/stable-diffusion-2-1-base"

                # Load with DDIM scheduler (deterministic, faster)
                self.scheduler = DDIMScheduler.from_pretrained(
                    model_id,
                    subfolder="scheduler"
                )

                self.pipe = StableDiffusionPipeline.from_pretrained(
                    model_id,
                    scheduler=self.scheduler,
                    torch_dtype=torch.float16 if self.device == "cuda" else torch.float32,
                    safety_checker=None,  # Disable for forensics
                    requires_safety_checker=False
                ).to(self.device)

                # Enable memory optimizations
                if self.device == "cuda":
                    self.pipe.enable_attention_slicing()

                self._from_cache = False
                logger.info("Stable Diffusion model loaded successfully")

                # Store in cache for future use
                self.cache.set(
                    self.cache_key,
                    {
                        'pipe': self.pipe,
                        'scheduler': self.scheduler
                    },
                    self.model_size_mb
                )
                logger.info(f"Cached model ({self.model_size_mb}MB) for future use")

            except Exception as e:
                # Do NOT re-raise. Cache the failure so every subsequent request
                # is not forced to retry a potential ~4-5 GB SD 2.1 download.
                logger.error(
                    "Failed to load Stable Diffusion model (%s) — DIRE will return "
                    "neutral results for all subsequent requests. Run: "
                    "git lfs pull && check diffusers install.", e,
                )
                self.pipe      = None
                self.scheduler = None
            finally:
                # Always set — prevents per-request retry on failure
                self._model_loaded = True

    def _preprocess_image(self, image_bytes: bytes) -> torch.Tensor:
        """
        Preprocess image for diffusion model.

        Args:
            image_bytes: Raw image bytes

        Returns:
            Pixel-space tensor (1, 3, 512, 512), values in [-1, 1].
        """
        from io import BytesIO

        # Load image
        img = Image.open(BytesIO(image_bytes)).convert('RGB')

        # Resize to 512x512 (SD training size)
        img = img.resize((512, 512), Image.LANCZOS)

        # Convert to tensor [-1, 1]
        img_tensor = torch.from_numpy(np.array(img)).float() / 255.0
        img_tensor = img_tensor * 2.0 - 1.0

        # Rearrange to (C, H, W)
        img_tensor = img_tensor.permute(2, 0, 1).unsqueeze(0)

        return img_tensor.to(self.device)

    def _encode_to_latent(self, pixels: torch.Tensor) -> torch.Tensor:
        """
        Encode a pixel-space tensor (1, 3, 512, 512) into the VAE latent
        space (1, 4, 64, 64) that the UNet expects.

        The 0.18215 factor is SD's VAE scaling constant — it brings the
        raw VAE posterior to approximately unit variance, matching the
        scale the UNet was trained on.
        """
        with torch.no_grad():
            latent_dist = self.pipe.vae.encode(
                pixels.to(self.pipe.vae.dtype)
            ).latent_dist
            latents = latent_dist.sample() * 0.18215
        return latents.to(self.device)

    def _decode_from_latent(self, latents: torch.Tensor) -> torch.Tensor:
        """
        Decode a VAE latent (1, 4, 64, 64) back to pixel space
        (1, 3, 512, 512), values in [-1, 1].
        """
        with torch.no_grad():
            pixels = self.pipe.vae.decode(
                latents.to(self.pipe.vae.dtype) / 0.18215
            ).sample
        return pixels.to(self.device)

    def _add_noise(self, image: torch.Tensor, timestep=50, generator=None) -> torch.Tensor:
        """
        Add noise to a latent (forward diffusion).

        Args:
            image:     Clean latent tensor (1, 4, 64, 64).
            timestep:  Scalar timestep value or tensor.
            generator: Optional torch.Generator for reproducible noise.
                       BUG FIX: previously no generator= was passed at all,
                       drawing from PyTorch's shared GLOBAL default RNG.
                       main.py seeds that RNG once at process start
                       (torch.manual_seed(42)) — only the FIRST DIRE call
                       after startup got that seed; every subsequent call
                       (any image, any request) drew different noise,
                       producing a different score for the SAME image
                       analyzed twice. Passing a per-image seeded
                       generator (see detect()) restores determinism.

        Returns:
            Noised latent tensor.
        """
        if generator is not None:
            noise = torch.randn(image.shape, generator=generator, device=generator.device, dtype=image.dtype).to(image.device)
        else:
            noise = torch.randn_like(image)
        ts = timestep if torch.is_tensor(timestep) else torch.tensor([timestep], device=self.device)
        noisy_image = self.scheduler.add_noise(image, noise, ts)
        return noisy_image

    def _denoise(self, noisy_image: torch.Tensor, steps: int = 20) -> torch.Tensor:
        """
        Denoise a latent (reverse diffusion).

        Args:
            noisy_image: Noised latent tensor (1, 4, 64, 64).
            steps:       Number of denoising steps.

        Note: self.scheduler.set_timesteps(steps) must be called by detect()
        BEFORE _add_noise so that the noise level and the first denoising
        timestep are aligned. Calling set_timesteps here (after noising) would
        produce a timestep mismatch and garbage reconstructions.

        Returns:
            Reconstructed latent tensor.
        """
        # Start from noisy latent
        latent = noisy_image

        # Iterative denoising
        with torch.no_grad():
            for t in self.scheduler.timesteps:
                # Predict noise
                latent_model_input = latent
                noise_pred = self.pipe.unet(
                    latent_model_input,
                    t,
                    encoder_hidden_states=torch.zeros(
                        (1, 77, 1024), 
                        device=self.device
                    )
                ).sample

                # Remove predicted noise
                latent = self.scheduler.step(noise_pred, t, latent).prev_sample

        return latent

    def _compute_reconstruction_error(
        self, 
        original: torch.Tensor, 
        reconstructed: torch.Tensor
    ) -> float:
        """
        Compute Mean Squared Error between original and reconstructed.

        Args:
            original: Original image tensor
            reconstructed: Reconstructed image tensor

        Returns:
            MSE value (lower = better reconstruction = more likely AI)
        """
        mse = torch.mean((original - reconstructed) ** 2).item()
        return mse

    def detect(self, image_bytes: bytes, filename: str = "unknown") -> Dict[str, Any]:
        """
        Detect if image is AI-generated using DIRE method.

        Args:
            image_bytes: Raw image bytes
            filename: Image filename for logging

        Returns:
            Detection result with score, confidence, explanation
        """
        try:
            # Lazy load model (uses cache if available - 10x faster!)
            self._load_model()

            logger.info(f"Running DIRE detection on {filename}")

            # 1. Preprocess to pixel space (1, 3, 512, 512), values in [-1, 1]
            pixels = self._preprocess_image(image_bytes)

            # 2. Encode pixels → VAE latent (1, 4, 64, 64).
            #    The UNet operates on latents, not on raw pixel tensors.
            #    (Previous code passed pixel tensors to vae.decode() — wrong shape.)
            latents = self._encode_to_latent(pixels)

            # 3. Set up the reverse-diffusion schedule BEFORE noising so
            #    _add_noise can use the correct start timestep. Calling
            #    set_timesteps after noising would misalign noise level and
            #    denoising loop start.
            denoise_steps = 20
            self.scheduler.set_timesteps(denoise_steps)
            start_timestep = self.scheduler.timesteps[0]

            # 4. Forward diffusion — noise the latents at the schedule's
            #    start timestep so _denoise can fully reconstruct them.
            # Seed derived from full image content (same pattern as
            # mcmc_engine.py's own seed-collision fix) so the SAME image
            # always gets the SAME noise, distinct images get independent draws.
            import hashlib as _hashlib
            _seed = int.from_bytes(_hashlib.sha256(image_bytes).digest()[:8], "big") % (2**31)
            _generator = torch.Generator(device="cpu").manual_seed(_seed)
            noisy_latents = self._add_noise(latents, timestep=start_timestep, generator=_generator)

            # 5. Reverse diffusion — iteratively denoise in latent space.
            reconstructed_latents = self._denoise(noisy_latents, steps=denoise_steps)

            # 6. Decode both original and reconstructed latents to pixel space
            #    for a like-for-like MSE comparison.
            reconstructed_pixels = self._decode_from_latent(reconstructed_latents)
            error = self._compute_reconstruction_error(pixels, reconstructed_pixels)

            # Convert error to AI probability score
            # Lower error = better reconstruction = more likely AI
            # Normalize: error typically in [0.001, 0.1] range
            normalized_error = min(error * 20, 1.0)
            ai_score = 1.0 - normalized_error

            # Generate explanation
            if error < 0.015:
                explanation = f"Very low reconstruction error ({error:.4f}) - strong diffusion signature"
                threshold_msg = "Very likely AI (excellent fit to diffusion model)"
            elif error < 0.030:
                explanation = f"Low reconstruction error ({error:.4f}) - likely diffusion-generated"
                threshold_msg = "Likely AI (good fit to diffusion model)"
            elif error < 0.050:
                explanation = f"Moderate reconstruction error ({error:.4f}) - uncertain"
                threshold_msg = "Uncertain (moderate fit)"
            else:
                explanation = f"High reconstruction error ({error:.4f}) - likely authentic"
                threshold_msg = "Likely real (poor fit to diffusion model)"

            cache_status = "cached" if self._from_cache else "fresh"
            logger.info(
                f"DIRE detection complete: error={error:.4f}, "
                f"score={ai_score:.3f} ({cache_status})"
            )

            return {
                "signal_name": "DIRE Reconstruction Error",
                "score": float(ai_score),
                "confidence": 0.95,
                "explanation": explanation,
                "raw_value": float(error),
                "expected_range": "< 0.030 for AI",
                "available": True,
                "method": "diffusion_reconstruction",
                "from_cache": self._from_cache,
                "threshold_interpretation": threshold_msg
            }

        except Exception as e:
            logger.warning(f"DIRE detection failed: {e}")
            return {
                "signal_name": "DIRE Reconstruction Error",
                "score": 0.5,  # Neutral on failure
                "confidence": 0.0,
                "explanation": f"Analysis failed: {str(e)}",
                "raw_value": 0.0,
                "expected_range": "N/A",
                "available": False,
                "method": "diffusion_reconstruction",
                "from_cache": False
            }

    def cleanup(self):
        """
        Free GPU memory.
        
        Note: Model stays in cache for reuse. Only clears GPU cache.
        """
        if self.device == "cuda":
            torch.cuda.empty_cache()
            
            if self._from_cache:
                logger.info("GPU cache cleared (model preserved in cache)")
            else:
                logger.info("GPU cache cleared (model cached for future use)")
