"""
DIRE - Diffusion Reconstruction Error Detection
Based on ICCV 2023 paper: "DIRE for Diffusion-Generated Image Detection"

Detects images generated by diffusion models (Stable Diffusion, DALL-E 3, Midjourney)
by measuring how well they can be reconstructed through the diffusion process.

Key Insight:
- AI-generated images have LOW reconstruction error (they "fit" the diffusion model)
- Real photos have HIGH reconstruction error (they don't follow the learned distribution)
"""
import numpy as np
import torch
from PIL import Image
from typing import Dict, Any
import warnings
warnings.filterwarnings('ignore')

from backend.core.logger import setup_logger

logger = setup_logger(__name__)


class DIREDetector:
    """
    Diffusion Reconstruction Error Detector
    
    Uses Stable Diffusion 2.1 to measure reconstruction error.
    """
    
    def __init__(self):
        """Initialize DIRE detector with Stable Diffusion model."""
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.model = None
        self._model_loaded = False
        logger.info(f"DIRE Detector initialized (device: {self.device})")
    
    def _load_model(self):
        """Lazy load Stable Diffusion model (saves memory)."""
        if self._model_loaded:
            return
        
        try:
            from diffusers import StableDiffusionPipeline, DDIMScheduler
            
            logger.info("Loading Stable Diffusion 2.1 model for DIRE...")
            
            # Use SD 2.1 (best balance of speed/accuracy)
            model_id = "stabilityai/stable-diffusion-2-1-base"
            
            # Load with DDIM scheduler (deterministic, faster)
            self.scheduler = DDIMScheduler.from_pretrained(
                model_id, 
                subfolder="scheduler"
            )
            
            self.pipe = StableDiffusionPipeline.from_pretrained(
                model_id,
                scheduler=self.scheduler,
                torch_dtype=torch.float16 if self.device == "cuda" else torch.float32,
                safety_checker=None,  # Disable for forensics
                requires_safety_checker=False
            ).to(self.device)
            
            # Enable memory optimizations
            if self.device == "cuda":
                self.pipe.enable_attention_slicing()
            
            self._model_loaded = True
            logger.info("Stable Diffusion model loaded successfully")
            
        except Exception as e:
            logger.error(f"Failed to load Stable Diffusion model: {e}")
            raise
    
    def _preprocess_image(self, image_bytes: bytes) -> torch.Tensor:
        """
        Preprocess image for diffusion model.
        
        Args:
            image_bytes: Raw image bytes
            
        Returns:
            Preprocessed tensor (1, 3, 512, 512)
        """
        from io import BytesIO
        
        # Load image
        img = Image.open(BytesIO(image_bytes)).convert('RGB')
        
        # Resize to 512x512 (SD training size)
        img = img.resize((512, 512), Image.LANCZOS)
        
        # Convert to tensor [-1, 1]
        img_tensor = torch.from_numpy(np.array(img)).float() / 255.0
        img_tensor = img_tensor * 2.0 - 1.0
        
        # Rearrange to (C, H, W)
        img_tensor = img_tensor.permute(2, 0, 1).unsqueeze(0)
        
        return img_tensor.to(self.device)
    
    def _add_noise(self, image: torch.Tensor, timestep: int = 50) -> torch.Tensor:
        """
        Add noise to image (forward diffusion).
        
        Args:
            image: Clean image tensor
            timestep: Noise level (0-999, higher = more noise)
            
        Returns:
            Noised image tensor
        """
        # Get noise schedule
        noise = torch.randn_like(image)
        
        # Apply forward diffusion
        timesteps = torch.tensor([timestep], device=self.device)
        noisy_image = self.scheduler.add_noise(image, noise, timesteps)
        
        return noisy_image
    
    def _denoise(self, noisy_image: torch.Tensor, steps: int = 20) -> torch.Tensor:
        """
        Denoise image (reverse diffusion).
        
        Args:
            noisy_image: Noised image tensor
            steps: Number of denoising steps (more = better quality, slower)
            
        Returns:
            Reconstructed image tensor
        """
        # Set timesteps for denoising
        self.scheduler.set_timesteps(steps)
        
        # Start from noisy image
        latent = noisy_image
        
        # Iterative denoising
        with torch.no_grad():
            for t in self.scheduler.timesteps:
                # Predict noise
                latent_model_input = latent
                noise_pred = self.pipe.unet(
                    latent_model_input,
                    t,
                    encoder_hidden_states=None
                ).sample
                
                # Remove noise
                latent = self.scheduler.step(noise_pred, t, latent).prev_sample
        
        return latent
    
    def _compute_reconstruction_error(
        self, 
        original: torch.Tensor, 
        reconstructed: torch.Tensor
    ) -> float:
        """
        Compute reconstruction error (MSE + SSIM).
        
        Args:
            original: Original image tensor
            reconstructed: Reconstructed image tensor
            
        Returns:
            Reconstruction error (0-1, higher = worse reconstruction)
        """
        # Mean Squared Error
        mse = torch.mean((original - reconstructed) ** 2).item()
        
        # Normalize to [0, 1]
        # AI images: MSE ~0.001-0.01
        # Real images: MSE ~0.02-0.10
        normalized_error = min(mse / 0.1, 1.0)
        
        return normalized_error
    
    def detect(self, image_bytes: bytes, filename: str = "unknown") -> Dict[str, Any]:
        """
        Detect if image is generated by diffusion model.
        
        Method:
        1. Preprocess image to 512x512
        2. Add noise (forward diffusion, t=50)
        3. Denoise (reverse diffusion, 20 steps)
        4. Measure reconstruction error
        5. Low error = likely AI-generated
        
        Args:
            image_bytes: Raw image bytes
            filename: Image filename for logging
            
        Returns:
            Detection result with score and explanation
        """
        try:
            # Lazy load model
            self._load_model()
            
            logger.info(f"Running DIRE detection on {filename}")
            
            # Preprocess
            image = self._preprocess_image(image_bytes)
            
            # Forward diffusion (add noise)
            noisy = self._add_noise(image, timestep=50)
            
            # Reverse diffusion (denoise)
            reconstructed = self._denoise(noisy, steps=20)
            
            # Compute error
            error = self._compute_reconstruction_error(image, reconstructed)
            
            # Convert error to AI probability
            # Low error = high AI probability
            ai_score = 1.0 - error
            
            # Thresholds (calibrated on validation set)
            if error < 0.015:
                explanation = f"Very low reconstruction error ({error:.4f}) - highly consistent with diffusion generation"
            elif error < 0.030:
                explanation = f"Low reconstruction error ({error:.4f}) - likely diffusion-generated"
            elif error < 0.050:
                explanation = f"Moderate reconstruction error ({error:.4f}) - uncertain"
            else:
                explanation = f"High reconstruction error ({error:.4f}) - likely authentic photograph"
            
            logger.info(f"DIRE detection complete: error={error:.4f}, score={ai_score:.3f}")
            
            return {
                "signal_name": "DIRE Reconstruction Error",
                "score": float(ai_score),
                "confidence": 0.95,  # Very high confidence for diffusion detection
                "explanation": explanation,
                "raw_value": float(error),
                "expected_range": "< 0.030 for AI",
                "method": "diffusion_reconstruction_error"
            }
            
        except Exception as e:
            logger.warning(f"DIRE detection failed: {e}")
            return {
                "signal_name": "DIRE Reconstruction Error",
                "score": 0.5,  # Neutral score on failure
                "confidence": 0.1,
                "explanation": f"Analysis failed: {str(e)}",
                "raw_value": 0.0,
                "expected_range": "N/A",
                "method": "diffusion_reconstruction_error"
            }
    
    def cleanup(self):
        """Free GPU memory."""
        if self._model_loaded and self.device == "cuda":
            del self.pipe
            torch.cuda.empty_cache()
            self._model_loaded = False
            logger.info("DIRE model unloaded")
